modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://github.com/lukebemish/codecutils/issues"
license = "LGPL v3"

[[mods]]
modId = "codecutils"
version = "${file.jarVersion}"
displayName = "Codec Utils"
authors = "Luke Bemish"
description = '''
Description here
'''
# logoFile = "icon.png"

[[dependencies.codecutils]]
modId = "forge"
mandatory = true
versionRange = "[41.0.94,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.codecutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
